# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPL_get_bbox <- function(sf, depth = 0L) {
    .Call('_lwgeom_CPL_get_bbox', PACKAGE = 'lwgeom', sf, depth)
}

CPL_lwgeom_version <- function(b = FALSE) {
    .Call('_lwgeom_CPL_lwgeom_version', PACKAGE = 'lwgeom', b)
}

CPL_make_valid <- function(sfc) {
    .Call('_lwgeom_CPL_make_valid', PACKAGE = 'lwgeom', sfc)
}

CPL_split <- function(sfc, blade) {
    .Call('_lwgeom_CPL_split', PACKAGE = 'lwgeom', sfc, blade)
}

CPL_geohash <- function(sfc, prec) {
    .Call('_lwgeom_CPL_geohash', PACKAGE = 'lwgeom', sfc, prec)
}

CPL_lwgeom_transform <- function(sfc, p4s) {
    .Call('_lwgeom_CPL_lwgeom_transform', PACKAGE = 'lwgeom', sfc, p4s)
}

CPL_hex_to_raw <- function(cx) {
    .Call('_lwgeom_CPL_hex_to_raw', PACKAGE = 'lwgeom', cx)
}

CPL_raw_to_hex <- function(raw) {
    .Call('_lwgeom_CPL_raw_to_hex', PACKAGE = 'lwgeom', raw)
}

CPL_read_wkb <- function(wkb_list, EWKB = FALSE, spatialite = FALSE, endian = 0L) {
    .Call('_lwgeom_CPL_read_wkb', PACKAGE = 'lwgeom', wkb_list, EWKB, spatialite, endian)
}

CPL_write_wkb <- function(sfc, EWKB = FALSE, endian = 0L, dim = "XY", precision = 0.0) {
    .Call('_lwgeom_CPL_write_wkb', PACKAGE = 'lwgeom', sfc, EWKB, endian, dim, precision)
}

