# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPL_lwgeom_version <- function(b = FALSE) {
    .Call('_lwgeom_CPL_lwgeom_version', PACKAGE = 'lwgeom', b)
}

CPL_make_valid <- function(sfc) {
    .Call('_lwgeom_CPL_make_valid', PACKAGE = 'lwgeom', sfc)
}

CPL_split <- function(sfc, blade) {
    .Call('_lwgeom_CPL_split', PACKAGE = 'lwgeom', sfc, blade)
}

CPL_geohash <- function(sfc, prec) {
    .Call('_lwgeom_CPL_geohash', PACKAGE = 'lwgeom', sfc, prec)
}

CPL_lwgeom_transform <- function(sfc, p4s) {
    .Call('_lwgeom_CPL_lwgeom_transform', PACKAGE = 'lwgeom', sfc, p4s)
}

CPL_minimum_bounding_circle <- function(sfc) {
    .Call('_lwgeom_CPL_minimum_bounding_circle', PACKAGE = 'lwgeom', sfc)
}

